# Generated by Django 5.2.3 on 2025-06-29 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('adres', models.TextField()),
                ('tel', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sirket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('adres', models.TextField()),
                ('tel', models.CharField(max_length=50)),
                ('mobil', models.CharField(max_length=50)),
                ('web', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('bank', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=34)),
                ('bic_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='urunler/')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kdv_orani', models.DecimalField(decimal_places=2, max_digits=4)),
                ('birim_kdv_tutari', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_no', models.CharField(max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.musteri')),
                ('bizim_firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.sirket')),
            ],
        ),
        migrations.CreateModel(
            name='FaturaUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.TextField()),
                ('adet', models.PositiveIntegerField()),
                ('kdvsiz_toplam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kdvli_toplam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.fatura')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.urun')),
            ],
        ),
        migrations.AddField(
            model_name='fatura',
            name='urunler',
            field=models.ManyToManyField(through='invoices.FaturaUrun', to='invoices.urun'),
        ),
    ]
