# Generated by Django 5.2.3 on 2025-06-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturaurun',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
